 
spring:
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB
      
  #jmx:
    #default-domain: rendezvous-now

  #mail:
    #protocol: smtp
    #host: mail.rendezvousnow.com
    #port: 465
    #username: no-reply@rendezvousnow.com
    #password: Poupinette1*
    #properties:
      #mail:
        #default-encoding: UTF-8
        #debug: true
        #smtp:
          #auth: true
          #starttls:
            #enable: true
            
            
  #mail:
    #protocol: smtp
    #host: smtp.gmail.com
    #port: 587
    #username: jupsfan@gmail.com
    #password: 04102012csepSCP4HWCGOOGLE
    #properties:
     # mail:
        #default-encoding: UTF-8
        #debug: true
        #smtp:
          #auth: true
          #starttls:
            #enable: true

    
logging:
   file: logs/logfiles.log
   

---
#Dev profile
server:  port: 8080
  servlet:    context-path: /

spring:
  profiles: local,default
  
  datasource:
    url: jdbc:mysql://localhost:3306/dbrdvnow?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC 
    username: rdvnow
    password: rdvnow
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
     
  jpa:
    show-sql: true
    
    hibernate:      ddl-auto: create-drop
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    
---

#Prod profile

server:
  port: 8080
  servlet:
    context-path: /
        
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost:3306/dbrdvnow?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC 
    username: rdvnow
    password: rdvnow
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
     
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

